languageCode = "en-us"
# in order for page menus to work correctly on posts, we need this set
baseurl = "https://softwareshepherds.github.io/EscapeVelocity/"
title = "2 devs, 1 blog (change this later)"
# theme = "hugo-cactus-theme"
# required for gh-pages
canonifyurls = true
publishdir = "public"

# hogo-minimalist-theme example settings
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
theme = "hugo-minimalist-theme"

[params]
    #params for authors.html partial are in /data/authors
    #partial is overriden in /layouts/partials/authors.html
    site_description = "To Develop Humans"
    header_background = "img/earth-space-header.jpg"
    header_title = "Escape Velocity"
    copyright = "2017 Software Shepards"
    custom_css = ['css/custom-styles.css']

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-109597824-1"

#social params are in /data/authors
#social layout overriden in /layouts/partials/social.html
